spring:
  config:
    import: application-secret.yml

  security:
    user:
      name: ${SWAGGER_USER}
      password: ${SWAGGER_PASSWORD}

  datasource:
    url: jdbc:mysql://slow-commit-db.cng6882sm6bl.ap-southeast-2.rds.amazonaws.com:3306/base
      ?serverTimezone=Asia/Seoul
      &characterEncoding=UTF-8
      &allowPublicKeyRetrieval=true
      &useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
server:
  port: 8080